spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.mysql: DEBUG

server:
  port: 8090
